app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class EditProfileForm(FlaskForm):
    first_name = StringField('Nome', validators=[Length(0, 64)])
    last_name = StringField('Cognome', validators=[Length(0, 64)])
    location = StringField('Località', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Salva')

app/auth.py
"""
In questo modulo si trovano tutte le route riguardandi l'autenticazione nel sito
"""
from flask import Blueprint, render_template

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    return render_template("login.html")


@auth.route('/logout')
def logout():
    return render_template("index.html")


@auth.route('/signup')
def sign_up():
    """
    TODO: creare pagina html corretta e gestire gli input salvandoli nel database,
          eventualmente mandando email di conferma
    """
    return render_template("index.html")

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, flash, url_for, redirect, Response
from flask_login import login_required, current_user
from sqlalchemy import case
import io
import csv

from .. models import *
from .. import db, moment
from ..quiz.forms import NewQuestionnaire
from . forms import EditProfileForm
from . import main
from sqlalchemy.dialects import postgresql


@main.route('/')
def index():
    if current_user.is_authenticated:
        return render_template('main/index.html')
    return render_template("main/index.html")


@main.route('/delete/<quiz_uuid>', methods=['POST'])
@login_required
def delete(quiz_uuid):
    quiz = Questionario.query.filter_by(uuid=quiz_uuid).first()
    domande = Domanda.query.filter_by(quiz_id=quiz.id).all()
    query3 = RisposteQuestionario.query.filter_by(quiz_id=quiz.id).all()
    for domanda in domande:
        query4 = PossibileRisposta.query.filter_by(question_id=domanda.id).all()
        for elem in query4:
            db.session.delete(elem)
        db.session.flush()
        db.session.delete(domanda)
        db.session.flush()
    for elem in query3:
        db.session.delete(elem)
    db.session.flush()
    db.session.delete(quiz)
    db.session.commit()

    flash('Questionario cancellato', 'success')
    return redirect(url_for('main.dashboard'))


@main.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    # query per prendere tutti i questionari dell'utente
    display_quiz = Questionario.query.filter_by(author_id=current_user.id).order_by(Questionario.id.desc()).all()

    # form
    nuovo_questionario_form = NewQuestionnaire()
    if nuovo_questionario_form.validate_on_submit():
        # registrazione dei dati passati dal form al db
        title = nuovo_questionario_form.titolo.data
        description = nuovo_questionario_form.descrizione.data
        nuovo = Questionario(title=title, description=description, author_id=current_user.id)
        db.session.add(nuovo)
        db.session.commit()
        flash('Questionario creato con successo', 'success')
        # una volta creato il questionario si viene reindirizzati all'editor
        return redirect(url_for('quiz.editor', edit_uuid=nuovo.uuid))
    return render_template('main/dashboard.html', nuovo_questionario_form=nuovo_questionario_form, quizzes=display_quiz)


@main.route('/profile/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template('main/user.html', user=user)


@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        current_user.location = form.location.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Modifiche salvate.', 'success')
        return redirect(url_for('.profile', username=current_user.username))
    form.first_name.data = current_user.first_name
    form.last_name.data = current_user.last_name
    form.location.data = current_user.location
    return render_template('main/profile.html', form=form)


@main.route('/quizzes')
@login_required
def quizzes():
    query = db.session.\
        query(
            Questionario.id,
            Questionario.title, Questionario.description, Questionario.description_html,
            Questionario.timestamp, Questionario.uuid, User.username).\
        join(
            Questionario, User.id == Questionario.author_id)

    lista_risposte = [risposta.quiz_id for risposta in RisposteQuestionario.query.filter_by(user_id=current_user.id).all()]

    return render_template('main/quizzes.html', questionari=query, risposte_date=lista_risposte)


@main.route('/responses/<quiz_uuid>')
@login_required
def responses(quiz_uuid):
    current_quiz = Questionario.query.filter_by(uuid=quiz_uuid).first()
    overview = get_overview(current_quiz.id)
    risposte = get_singole(current_quiz.id)
    return render_template('responses.html', current_quiz=current_quiz, overview=overview, risposte=risposte)


@main.route('/responses_overview/')
@login_required
def responses_overview():
    display_quiz = Questionario.query.filter_by(author_id=current_user.id).order_by(Questionario.id.desc()).all()
    return render_template('responses_overview.html', questionari=display_quiz)


def get_overview(quiz_id):
    subquery = db.session.query(RisposteQuestionario.id).filter(RisposteQuestionario.quiz_id == quiz_id)
    risposte = db.session.query(Domanda.text.label('Domanda'), Domanda.type_id.label('Tipo'),
                                Domanda.id.label('Id_domanda'),
                                case((RispostaDomanda.is_open, RispostaDomanda.text),
                                     else_=PossibileRisposta.text).label('Risposta')).join(RispostaDomanda) \
        .outerjoin(RispostaDomanda.have_as_answers).filter(RispostaDomanda.id.in_(subquery)) \
        .order_by(Domanda.id, RispostaDomanda.id)
    # print(str(risposte.statement.compile(dialect=postgresql.dialect())))
    overview = {}
    # formato dizionario:{("Domanda1","Tipo_di_domanda"):{"Risposta1":numero di risposte,"Risposta2":numero_di_risposte)
    # inizializzazione del dizionario
    # 1 = aperta
    # 2 = scelta
    # 3 = multipla
    for i in risposte:
        overview[(i.Domanda, i.Tipo)] = {}
        if i.Tipo != 1:
            possibili_risposte = PossibileRisposta.query.filter(PossibileRisposta.question_id == i.Id_domanda).all()
            for j in possibili_risposte:
                overview[(i.Domanda, i.Tipo)][j.text] = 0
    # valorizzazione delle riposte multiple nel dizionario
    for i in risposte:
        if i.Risposta is not None:
            if i.Tipo == 1:
                overview[(i.Domanda, i.Tipo)][i.Risposta] = 1
            else:
                overview[(i.Domanda, i.Tipo)][i.Risposta] += 1
    return overview


def get_singole(quiz_id):
    risposte_questionario = db.session.query(RisposteQuestionario.id).filter(RisposteQuestionario.quiz_id == quiz_id).all()
    risposte_singole = {}
    for r in risposte_questionario:
        i = r.id
        print(i)
        subquery = db.session.query(RisposteQuestionario.id).filter(RisposteQuestionario.quiz_id == quiz_id,
                                                                    RisposteQuestionario.id == i)
        risposte = db.session.query(Domanda.text.label('Domanda'),
                                    case((RispostaDomanda.is_open, RispostaDomanda.text),
                                         else_=PossibileRisposta.text).label('Risposta')).join(RispostaDomanda) \
            .outerjoin(RispostaDomanda.have_as_answers).filter(RispostaDomanda.id.in_(subquery)) \
            .order_by(Domanda.id, RispostaDomanda.id)
        for j in risposte:
            risposte_singole[i] = {}
        for j in risposte:
            if j.Domanda not in risposte_singole[i]:
                risposte_singole[i][j.Domanda] = [j.Risposta]
            else:
                risposte_singole[i][j.Domanda].append(j.Risposta)
    print(risposte_singole)
    return risposte_singole


@main.route('/download/csv/<uuid>')
@login_required
def download(uuid):
    # query per prendere il database e le risposte
    current_quiz = Questionario.query.filter_by(uuid=uuid).first()
    risposte = RisposteQuestionario.query.filter_by(quiz_id=current_quiz.id).all()

    # get singole restituisce un dizionario con le risposte ad ogni domanda nel formato
    # { key = risposta.id, value = dizionario{ domanda: risposta } }
    data = get_singole(current_quiz.id)

    '''
    generazione della lista con gli id delle risposte:
        dal momento che la variabile
    '''
    lista_risposte_id = [r.id for r in risposte]

    if not lista_risposte_id:
        flash('Il quiz non ha ancora ricevuto risposte, il file csv non verrà creato', 'warning')
        return redirect(url_for('.responses_overview', quiz_uuid=uuid))

    max_question_number = 0
    for x in range(0, len(data)):
        if len(data[lista_risposte_id[x]].keys()) > max_question_number:
            max_question_number = x

    # stream output
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=data[lista_risposte_id[max_question_number]].keys())

    writer.writeheader()
    for i in range(0, len(data)):
        writer.writerow(data[lista_risposte_id[i]])

    output.seek(0)
    return Response(output,
                    mimetype="text/csv",
                    headers={f"Content-Disposition": f"attachment;filename={current_quiz.title}.csv"})

app/templates/main/dashboard.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block page_content %}
    <style>
        a {
            text-decoration: none !important;
            color: black
        }
    </style>

<div class="container-fluid">
    <div class="d-sm-flex justify-content-between align-items-center mb-4">
        <h3 class="text-dark mb-0">Crea un questionario</h3>
    </div>
    <div class="row">
        <div class="col-md-6 col-xl-3 mb-4">
            <div class="card textwhite bg-primary text-white border-start-primary shadow">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newQuizModal">
                <div class="card-body">
                    <div class="row align-items-center no-gutters">
                        <div class="col me-2">
                            <div class="text-white fw-bold h5 mb-0"><span>Nuovo questionario</span></div>
                        </div>
                        <div class="col-auto"><i class="fas fa-plus fa-2x text-gray-300"></i></div>
                    </div>
                </div>
                </button>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="newQuizModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Nuovo questionario</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="" method="POST" role="form" class="user">
                        <div class="modal-body">
                            {{ nuovo_questionario_form.hidden_tag() }}
                            {{ nuovo_questionario_form.titolo(class='form-text form-control', placeholder='Titolo') }}
                            <hr>
                            {{ nuovo_questionario_form.descrizione(class='form-text form-control', placeholder='Descrizione') }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
                            {{ nuovo_questionario_form.submit(class='btn btn-primary') }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- end Modal -->

        <!--
        <div class="col-md-6 col-xl-3 mb-4">
            <div class="card shadow border-start-info py-2">
                <div class="card-body">
                    <div class="row align-items-center no-gutters">
                        <div class="col me-2">
                            <div class="text-uppercase text-info fw-bold text-xs mb-1"><span>Tasks</span></div>
                            <div class="row g-0 align-items-center">
                                <div class="col-auto">
                                    <div class="text-dark fw-bold h5 mb-0 me-3"><span>50%</span></div>
                                </div>
                                <div class="col">
                                    <div class="progress progress-sm">
                                        <div class="progress-bar bg-info" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%;"><span class="visually-hidden">50%</span></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto"><i class="fas fa-clipboard-list fa-2x text-gray-300"></i></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-xl-3 mb-4">
            <div class="card shadow border-start-warning py-2">
                <div class="card-body">
                    <div class="row align-items-center no-gutters">
                        <div class="col me-2">
                            <div class="text-uppercase text-warning fw-bold text-xs mb-1"><span>Pending Requests</span></div>
                            <div class="text-dark fw-bold h5 mb-0"><span>18</span></div>
                        </div>
                        <div class="col-auto"><i class="fas fa-comments fa-2x text-gray-300"></i></div>
                    </div>
                </div>
            </div>
        </div>-->
    </div>
    <!-- Start: Chart -->
    <div class="row">
        <!-- OVERVIEW DEI QUESTIONARI -->
        <div class="col-xl-6 col-lg-10 col-md-10 col-sm-12">
            <div class="card shadow mb-4">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h6 class="text-primary fw-bold m-0">Overview: i tuoi questionari</h6>
                    <div class="dropdown no-arrow"><button class="btn btn-link btn-sm dropdown-toggle" aria-expanded="false" data-bs-toggle="dropdown" type="button"><i class="fas fa-ellipsis-v text-gray-400"></i></button>
                        <div class="dropdown-menu shadow dropdown-menu-end animated--fade-in">
                            <p class="text-center dropdown-header">Opzioni</p>
                            <a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#newQuizModal">Nuovo questionario</a>
                            <a class="dropdown-item" href="#">Cancella tutti</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <ul class="list-group list-group-flush">
                    {% if quizzes %}
                        {% for result in quizzes %}
                            <li class="list-group-item">
                                <div class="row align-items-center no-gutters">

                                    <div class="col-5 col-sm-4">
                                        <h6 class="mb-0"><strong><a href="{{ url_for('quiz.editor',edit_uuid=result.uuid) }}">{{ result.title }}</a></strong></h6><span class="text-xs">{{ moment(result.timestamp).format('LLL') }}</span>
                                    </div>
                                     <div class="col-5 col-sm-4">
                                        <p class="mb-0 text-black-50">
                                            {% if result.description_html %}
                                                {% if result.description_html|length > 50 %}
                                                    {{ result.description[:20]+'...' | safe }}
                                                {% else %}
                                                    {{ result.description_html | safe }}
                                                {% endif %}
                                            {% else %}
                                                {%  if result.description|length > 20 %}
                                                    {{ result.description[:20]+'...' }}
                                                {% else %}
                                                    {{ result.description }}
                                                {% endif %}
                                            {% endif %}
                                        </p>
                                    </div>
                                    <div class="col-1 col-sm-2">
                                        <form id="delete-quiz" method="POST" action="{{ url_for('main.delete', quiz_uuid=result.uuid) }}">
                                            <button type="submit" class="btn btn-outline-danger fas fa-trash-alt"></button>
                                        </form>
                                    </div>
                                    <div class="col-1 col-sm-2">
                                        <form id="edit-quiz" method="GET" action="{{ url_for('quiz.editor', edit_uuid=result.uuid) }}">
                                            <button type="submit" class="btn btn-outline-info fas fa-edit" ></button>
                                        </form>
                                    </div>
                                </div>
                                <div class="row align-items-center no-gutters">
                                    <div class="col-lg-12 col-12 col-sm-12">
                                        <form id="delete-quiz" method="GET" action="{{ url_for('main.responses', quiz_uuid=result.uuid) }}">
                                                <button type="submit" class="btn btn-outline-primary">Visualizza risposte</button>
                                        </form>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                        {% else %}
                        <li class="list-group-item">
                            <div class="row align-items-center no-gutters">
                                <div class="col me-2">
                                    <h6 class="small fw-bold mb-0">Non hai ancora creato nessun questionario!</h6>
                                </div>
                            </div>
                        </li>
                    {% endif %}
                    </ul>
                </div>
            </div>
        <!-- fine: OVERVIEW DEI QUESTIONARI -->
        </div>
    </div>
</div>
    <script src="{{ url_for('static', filename='js/chart.min.js') }}"></script>
{% endblock %}

app/templates/main/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block page_content %}

<div class="container-fluid">
    <div class="row align-items-center mb-4">
        {%  if current_user.is_authenticated %}
            <div class="page-header"><h1>Benvenuto {{ current_user.username.capitalize() }}!</h1></div>
            <div class="page-header"><h1>Comincia subito a creare un quiz cliccando su "Crea un Questionario"!</h1></div>
        {% else %}
            <div class="page-header"><h1>Ciao Anonimo!</h1></div>
            <div class="text-dark">Effettua il <a href="{{ url_for('auth.login') }}">login</a> per utilizzare il servizio.</div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/main/profile.html
{% extends 'layout.html' %}

{% block title %}Profilo{% endblock %}

{% block page_content %}
    <h3 class="text-dark mb-4">Profilo</h3>
    <div class="row mb-3">
        <div class="col-lg-8">
            <div class="row">
                <div class="col">
                    <div class="card shadow mb-3">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">Impostazioni</p>
                        </div>
                        <div class="card-body">
                            <form method="POST">
                                {{ form.hidden_tag() }}
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-3">
                                            {{ form.first_name.label(class='form-label') }}
                                            {{ form.first_name(class='form-control') }}
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="mb-3">
                                            {{ form.last_name.label(class='form-label') }}
                                            {{ form.last_name(class='form-control') }}
                                        </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <div class="mb-3">
                                            {{ form.location.label(class='form-label') }}
                                            {{ form.location(class='form-control') }}
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-3">{{ form.submit(class='btn btn-primary btn-sm') }}</div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/main/quizzes.html
{% extends 'layout.html' %}

{% block title %}Questionari{% endblock %}

{% block page_content %}
    <style>
        a {
            text-decoration: none !important;
            color: black
        }
    </style>
    <div class="container-fluid">
        <div class="row align-items-center mb-4">
            {%  if current_user.is_authenticated %}
                <div class="page-header"><h1>Ciao {{ current_user.username.capitalize() }}, qui potrai compilare tutti i questionari creati dagli utenti </h1></div>
            {% else %}
                <div class="page-header"><h1>Ciao Anonimo!</h1></div>
                <div class="text-dark">Effettua il <a href="{{ url_for('auth.login') }}">login</a> per utilizzare il servizio.</div>
            {% endif %}
        </div>
    </div>
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center text-center">
            <h3>Lista dei questionari</h3>
        </div>
        <div class="card-body">
            <table id="data" class="table table-hover table-striped">
                <thead>
                <tr>
                    <th scope="col">Titolo</th>
                    <th scope="col">Descrizione</th>
                    <th scope="col">Data</th>
                    <th scope="col">Autore</th>
                </tr>
                </thead>
                <tbody>
                {% for questionario in questionari %}
                    {% if (questionario.username != current_user.username) and (questionario.id not in risposte_date) %}
                    <tr>
                        <td><a href="{{ url_for('quiz.render', questionnaire_uuid=questionario.uuid) }}">{{ questionario.title }}</a></td>
                        <td>
                            {% if questionario.description_html %}
                                {% if questionario.description_html|length > 50 %}
                                    {{ questionario.description[:40]+'...' | safe }}
                                {% else %}
                                    {{ questionario.description_html | safe }}
                                {% endif %}
                            {% else %}
                                {%  if questionario.description|length > 40 %}
                                    {{ questionario.description[:40]+'...' }}
                                {% else %}
                                    {{ questionario.description }}
                                {% endif %}
                            {% endif %}
                        </td>

                        <td>{{ moment(questionario.timestamp).format('LLL') }}</td>
                        <td>
                            <a href="{{ url_for('main.profile', username=questionario.username) }}">{{ questionario.username }}</a>
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block script_part %}
    <script>
    $(document).ready(function () {
      $('#data').DataTable({
        columns: [
          null,
          null,
          {searchable: false},
          null],
      });
    });
  </script>
{% endblock %}

app/templates/main/user.html
{% extends 'layout.html' %}

{% block title %}{{ user.username }}{% endblock %}

{%  block page_content %}
    <div class="page-header">
    <div class="profile-header">
        <h1>Ciao {{ user.username }}!</h1>
        {% if user.first_name or user.location %}
        <p>
            {% if user.first_name %}{{ user.first_name }} {{ user.last_name }}<br>{% endif %}
            {% if user.location %}
                di <a href="http://maps.google.com/?q={{ user.location }}">{{ user.location }}</a><br>
            {% endif %}
        </p>
        {% endif %}
        <p>Indirizzo E-Mail collegato: <a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
        <p>{% if user.member_since %}Membro da {{ moment(user.member_since).format('LL') }}. {% endif %} Ultimo accesso {{ moment(user.last_seen).fromNow() }}.</p>
        {% if user == current_user %}
        <p>Hai creato un totale di <a href="{{ url_for('main.dashboard') }}">{{ user.quizzes.count() }}</a> questionari. Keep on quizzing!</p>
        {% else %}
        <p>Questo utente ha creato {{ user.quizzes.count() }} questionari.</p>
        {% endif %}
        <p>
            {% if user == current_user %}
            <a class="btn btn-outline-info" href="{{ url_for('.edit_profile') }}">Modifica Profilo</a>
            {% endif %}
        </p>
    </div>
</div>
{% endblock %}