app/quiz/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SubmitField, SelectField, SelectMultipleField
from wtforms.validators import Required, Length, Optional
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from flask_pagedown.fields import PageDownField
from wtforms import widgets
from ..models import *
from .. import db

# QUIZ CREATION
''' at the moment in DB:
dropdown_question_types:
    ('1', 'Aperta')
    ('2', 'A scelta multipla')
    ('3', 'A scelta singola')
    ('4', 'Numerica a interi')
'''

'''
Concept:
Dentro a editorForm vengono aggiunte le domande, quando schiaccio il + per una nuova domanda appare il module
per scegliere quale tipo di domanda fare e poi viene aggiunto il tipo corretto alla lista
'''


class Question(FlaskForm):
    text = PageDownField('Domanda', validators=[Required()])
    type_id = QuerySelectField('type',
                               validators=[Required()],
                               query_factory=lambda: TipologiaDomanda.query.all(),
                               get_label='name')
    is_activated = BooleanField('E\' attivata da altre domande?', id='is_activated')
    activant = SelectField('Domanda che attiva questa domanda', coerce=int, id='select_activant', validators=[Optional()])  # , validators=[Required()])
    id_activant_answer = SelectField('Risposta che deve attivare questa domanda', coerce=int,
                                     id='select_id_activant_answer', validators=[Optional()])  # , validators=[Required()])
    # category_id = QuerySelectField('Tag',
    #                               query_factory=lambda: CategoriaDomanda.query.all(),
    #                               get_label='name')
    invia = SubmitField('Crea')


class SingleAnswerForm(FlaskForm):
    text = StringField('Testo della risposta...')
    add = SubmitField('Aggiungi')


class EditForm(FlaskForm):
    text = PageDownField('Testo', validators=[Required()])
    # type_id = QuerySelectField('type',
    #                           validators=[Required()],
    #                           query_factory=lambda: TipologiaDomanda.query.all(),
    #                           get_label='name')
    # category_id = QuerySelectField('Tag',
    #                               query_factory=lambda: CategoriaDomanda.query.all(),
    #                               get_label='name')
    # activant = BooleanField('Attivante')
    # activable = BooleanField('Attivabile')
    # possible_answers = FieldList(FormField(PossibleAnswerForm, default=lambda: PossibileRisposta(), min_entries=1))
    submit = SubmitField('Salva')


class EditorForm(FlaskForm):
    title = StringField('Titolo')
    description = PageDownField('Descrizione')
    submit = SubmitField('Salva')


class NewQuestionnaire(FlaskForm):
    titolo = StringField('Titolo', validators=[Required()])
    descrizione = PageDownField('Descrizione')
    submit = SubmitField('Crea')


class MultiCheckboxField(SelectMultipleField):
    """
    A multiple-select, except displays a list of checkboxes.

    Iterating the field will produce subfields, allowing custom rendering of
    the enclosed checkbox fields.
    """
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()

app/quiz/__init__.py
from flask import Blueprint

quiz = Blueprint('quiz', __name__)

from . import views

app/quiz/views.py
from flask import render_template, flash, redirect, request, url_for, abort, jsonify
from flask_login import login_required, current_user
from sqlalchemy.exc import IntegrityError
from .forms import Question, EditorForm, EditForm, SingleAnswerForm, MultiCheckboxField
from . import quiz
from ..models import *
from .. import db, moment

from flask_wtf import FlaskForm

from wtforms import TextAreaField, SelectMultipleField, SubmitField, RadioField


@quiz.route('/editor/<edit_uuid>', methods=['GET', 'POST'])
@login_required
def editor(edit_uuid):
    # queries
    current_quiz = Questionario.query.filter_by(uuid=edit_uuid).first()
    tipi_domanda = TipologiaDomanda.query.all()
    subquery = db.session.query(TipologiaDomanda.id).filter(TipologiaDomanda.name == "Scelta")
    attivante = db.session.query(Domanda.id, Domanda.text).filter(Domanda.type_id.in_(subquery),
                                                                  Domanda.quiz_id == current_quiz.id)
    attivante_list = [(-1, '')]
    for i in attivante:
        attivante_list.append((i.id, i.text))

    id_list = [(-1, '')]
    for i in PossibileRisposta.query.all():
        id_list.append((i.id, i.text))

    # forms
    question = Question()
    question.activant.choices = attivante_list
    question.id_activant_answer.choices = id_list
    editor_form = EditorForm(obj=current_quiz)

    if question.invia.data and question.validate():
        valida = False
        if question.is_activated.data:
            insieme_valido = [(i.id, i.question_id) for i in PossibileRisposta.query.all()]
            if (question.id_activant_answer.data, question.activant.data) in insieme_valido:
                domanda = Domanda(text=question.text.data, type_id=question.type_id.data.id,
                                  is_activated=question.is_activated.data, quiz_id=current_quiz.id,
                                  activated_by=question.activant.data,
                                  activated_by_answer_id=question.id_activant_answer.data)
                valida = True
            else:
                flash('Non è stato possibile creare la domanda: Errore nella scelta della domanda o risposta attivante',
                      'warning')
        else:
            domanda = Domanda(text=question.text.data, type_id=question.type_id.data.id, quiz_id=current_quiz.id,
                              is_activated=question.is_activated.data)
            valida = True

        if valida:
            db.session.add(domanda)
            db.session.commit()
            flash('Nuova domanda creata', 'success')
            return redirect(url_for('quiz.editor', edit_uuid=current_quiz.uuid))

    if editor_form.submit.data and editor_form.validate():
        editor_form.populate_obj(current_quiz)
        db.session.commit()
        flash("Modifiche salvate", 'success')

    return render_template('quiz/editor.html', editor_form=editor_form,
                           form=question, current_quiz=current_quiz, tipi_domanda=tipi_domanda)


@quiz.route('/editor/<quiz_uuid>/<question_id>', methods=['GET', 'POST'])
@login_required
def edit_question(quiz_uuid, question_id):
    # query
    current_question = Domanda.query.filter_by(id=question_id).first()
    risposte = PossibileRisposta.query.filter_by(question_id=question_id).all()

    # forms
    risposte_form = SingleAnswerForm()
    form_dom = EditForm(obj=current_question)

    if risposte_form.add.data and risposte_form.validate():
        nuova_risp = PossibileRisposta(text=risposte_form.text.data, question_id=question_id)
        db.session.add(nuova_risp)
        db.session.commit()
        flash('Risposta aggiunta', 'success')
        return redirect(url_for('quiz.edit_question', quiz_uuid=quiz_uuid, question_id=question_id))

    if form_dom.submit.data and form_dom.validate():
        form_dom.populate_obj(current_question)
        db.session.commit()
        flash('Modifiche salvate', 'success')

    return render_template('quiz/question_editor.html', form=form_dom, risposte=risposte,
                           current_question=current_question, risposte_form=risposte_form,
                           quiz_uuid=quiz_uuid)


@quiz.route('/get_possible_answers')
def get_possible_answers():
    id_ = request.args.get('activant', type=int)
    print(id_)
    p_r = PossibileRisposta.query.filter_by(question_id=id_).all()
    possibili_risposte = [(i.id, i.text) for i in p_r]
    return jsonify(possibili_risposte)


@quiz.route('/delete/<domanda_id>', methods=['POST'])
@login_required
def delete(domanda_id):
    query1 = Domanda.query.filter_by(id=domanda_id).first()
    query2 = Questionario.query.filter_by(id=query1.quiz_id).first()
    query3 = PossibileRisposta.query.filter_by(question_id=domanda_id).all()

    if query1 and query2 and current_user.id == query2.author_id:
        for elem in query3:
            db.session.delete(elem)
        db.session.commit()
        db.session.delete(query1)
        db.session.commit()
        flash('Domanda rimossa', 'success')
        return redirect(url_for('quiz.editor', edit_uuid=query2.uuid))
    else:
        flash('Operazione invalida', 'danger')
        abort(403)


@quiz.route('/remove/<quiz_uuid>/<answer_id>', methods=['POST'])
@login_required
def delete_answer(answer_id, quiz_uuid):
    query = PossibileRisposta.query.filter_by(id=answer_id).first()
    db.session.delete(query)
    db.session.commit()

    return redirect(url_for('quiz.edit_question', quiz_uuid=quiz_uuid, question_id=query.question_id))


@quiz.route('/view/<questionnaire_uuid>', methods=['GET', 'POST'])
@login_required
def render(questionnaire_uuid):
    # query
    current_quiz = Questionario.query.filter_by(uuid=questionnaire_uuid).first()
    domande = current_quiz.questions.order_by(Domanda.id)

    # creazione dinamica del form lato server

    # prima di tutto viene creato il form vuoto con solo il campo submit
    class CompilationForm(FlaskForm):
        submit = SubmitField('Invia', render_kw={'class': 'btn btn-info'})
    iterator = 0

    # poi per ogni domanda del quiz viene creato il campo da compilare corretto a seconda del type_id
    # con setattr sono in grado di comporre dinamicamente il nome del campo che è
    # 'domanda' + il numero attuale dell'iteratore
    for domanda in domande:
        # se è una domanda aperta
        if domanda.type_id == 1:
            setattr(CompilationForm, 'domanda' + str(iterator), TextAreaField('Risposta aperta',
                                                                              render_kw={'class': 'form-control'}))
        # se è una domanda a scelta singola
        elif domanda.type_id == 3:
            setattr(CompilationForm, 'domanda' + str(iterator), RadioField(
                choices=[(q.id, q.text) for q in PossibileRisposta.query.filter_by(question_id=domanda.id)],
                render_kw={'class': 'form-check', 'type': 'radio'}
            ))
        # se è una domanda a scelta multipla
        else:
            setattr(CompilationForm, 'domanda' + str(iterator), MultiCheckboxField(
                choices=[(str(q.id), q.text) for q in PossibileRisposta.query.filter_by(question_id=domanda.id)],
                render_kw={'class': 'form-select'}
            ))
        iterator += 1

    # una volta aggiunti tutti i campi alla classe l'oggetto è pronto per essere istanziato
    form = CompilationForm()

    if form.validate_on_submit():
        # sto registrando una risposta: aggiungo il record al db
        new_record = RisposteQuestionario(user_id=current_user.id, quiz_id=current_quiz.id)
        db.session.add(new_record)
        db.session.flush()

        iterator = 0
        for dom in domande:
            # se è una domanda aperta viene registrato nel db il campo 'text'
            if dom.type_id == 1:
                req = request.form.get('domanda' + str(iterator))
                # il campo text è di tipo stringa e se viene lasciato vuoto è di tipo NoneType
                # quindi per non incorrere in errori con il seguente if si converte l'input None in String
                if req is None:
                    req = ''
                db.session.add(RispostaDomanda(
                    id=new_record.id, question_id=dom.id, is_open=True, text=req)
                )
            # se è una domanda a scelta invece viene salvata la scelta nella relazione molti-a-molti
            elif dom.type_id == 3:
                risp = RispostaDomanda(id=new_record.id, question_id=dom.id, is_open=False)
                db.session.add(risp)
                db.session.flush()
                statement = have_as_answer.insert().values(possible_answer_id=request.form.get('domanda' + str(iterator)),
                                                           answer_to_questions_id=risp.id,
                                                           question_id=dom.id)
                db.session.execute(statement)
            else:
                risp = RispostaDomanda(id=new_record.id, question_id=dom.id, is_open=False)
                db.session.add(risp)
                db.session.flush()
                for elem in request.form.getlist('domanda' + str(iterator)):
                    statement = have_as_answer.insert().values(
                        possible_answer_id=elem,
                        answer_to_questions_id=risp.id,
                        question_id=dom.id)
                    db.session.execute(statement)
                    db.session.flush()
            iterator += 1
        # alla fine dell'aggiunta di tutte le risposte si esegue un try per l'insert
        try:
            db.session.commit()
            flash('Risposta inviata', 'success')
            return redirect(url_for('main.quizzes'))
        except IntegrityError:
            # oppure si annulla tutto con un rollback
            flash('Si è verificato un errore nella registrazione della risposta', 'warning')
            db.session.rollback()

app/templates/quiz/editor.html
{% extends 'layout.html' %}

{% block title %}Editor{% endblock %}

{% block page_content %}

    <div class="container-fluid">
        <!-- FLASH ERRORI -->
        <div class="row mx-auto">
            <div class="container">
                {% if editor_form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        <ul class="errors">
                            {% for field_name, field_errors in editor_form.errors|dictsort if field_errors %}
                                {% for error in field_errors %}
                                    <li>{{ editor_form[field_name].label }}: {{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>

        <!-- new qiestion Modal -->
        <div class="modal fade" id="newQuestion" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Nuovo quiz</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="" method="POST" role="form" class="user">
                        <div class="modal-body">
                            {{ form.hidden_tag() }}
                            {{ form.text(class='form-text form-control', placeholder='Testo della domanda') }}
                            <hr>
                            {{ form.type_id(class='form-select') }}
                            <hr>
                            <!--{{ form.is_activated.label }} {{ form.is_activated(class='form-check-inline', onclick='visibile()') }}
                            <div id="divInvis" style="visibility: hidden">
                                <br>
                                {{ form.activant.label }} {{ form.activant(class='form-select') }}
                                <br>
                                {{ form.id_activant_answer.label }} {{ form.id_activant_answer(class='form-select') }}
                            </div>-->

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
                            {{ form.invia(class='btn btn-primary') }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- end Modal -->

        <!-- EDITOR -->
        <div class="page-header align-items-center mb-4">
            <h3 class="text-dark mb-0">Editor</h3>
        </div>
            <div class="card shadow mb-4 text-center col-md-7 mx-auto">
                <div class="card-header">
                    <form method="POST">
                    {{ editor_form.hidden_tag() }}
                    <h3>{{ editor_form.title(class='form-input') }}</h3>
                    {{ editor_form.description(class='form-control') }}
                    {{ editor_form.submit(class="btn btn-info") }}
                    </form>
                </div>
                <div class="card-body" data-toggle="fieldset" id="question-fieldset">
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Testo della domanda</th>
                                <!--<th scope="col">Viene attivata da una domanda</th>-->
                                <th scope="col">Tipo di domanda</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for domanda in current_quiz.questions %}
                                <tr data-toggle="fieldset-entry">
                                    <th scope="row">{{ loop.index0 + 1 }}</th>
                                    <td>
                                        {% if domanda.text_html %}
                                            {{ domanda.text_html | safe }}
                                        {% else %}
                                            {{ domanda.text }}
                                        {% endif %}
                                    </td>
                                    <!--<td>{{ domanda.is_activated }}</td>-->
                                    <td>{{ tipi_domanda[domanda.type_id - 1].name }}</td>
                                    <td>
                                        <form id="edit-question" method="POST" action="{{ url_for('quiz.edit_question', question_id=domanda.id, quiz_uuid=current_quiz.uuid) }}">
                                            <button type="submit" class="btn btn-outline-info fas fa-edit"></button>
                                        </form>
                                        <form id="delete-question" method="POST" action="{{ url_for('quiz.delete', domanda_id=domanda.id) }}">
                                            <button type="submit" class="btn btn-outline-danger fas fa-trash-alt"></button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newQuestion"><i class="fas fa-plus fa-2x text-white"></i></button>
                </div>
            </div>
    </div>
{% endblock %}
{% block script_part %}
    <script>
    function visibile(){
        if (document.getElementById('is_activated').checked)
        {
            document.getElementById('divInvis').style.visibility = 'visible';
        } else {
            document.getElementById('divInvis').style.visibility = 'hidden';
        }
    }
    </script>
    <script charset="utf-8" type="text/javascript">

        $(function() {

            // jQuery selection for the 2 select boxes
            var dropdown = {
                activant: $('#select_activant'),
                activant_answer: $('#select_id_activant_answer')
            };

            // call to update on load
            updatePossibleAnswers();

            // function to call XHR and update county dropdown
            function updatePossibleAnswers() {
                var send = {
                    activant: dropdown.activant.val()
                };
                dropdown.activant_answer.attr('disabled', 'disabled');
                dropdown.activant_answer.empty();
                $.getJSON("{{ url_for('quiz.get_possible_answers')}}", send, function(data) {
                    data.forEach(function(item) {
                        dropdown.activant_answer.append(
                            $('<option>', {
                                value: item[0],
                                text: item[1]
                            })
                        );
                    });
                    dropdown.activant_answer.removeAttr('disabled');
                });
            }

            // event listener to state dropdown change
            dropdown.activant.on('change', function() {
                updatePossibleAnswers();
            });

        });

    </script>
{% endblock %}

app/templates/quiz/question_editor.html
{% extends 'layout.html' %}

{% block title %}Edit question{% endblock %}

{% block page_content %}

    <div class="container-fluid">
        <!-- errors display -->
        <div class="row mx-auto">
            <div class="container">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        <ul class="errors">
                            {% for field_name, field_errors in form.errors|dictsort if field_errors %}
                                {% for error in field_errors %}
                                    <li>{{ form[field_name].label }}: {{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>


        <!-- new qiestion Modal -->
        <div class="modal fade" id="newAnswer" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Aggiungi risposta</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="" method="POST" role="form" class="user">
                        <div class="modal-body">
                            {{ risposte_form.hidden_tag() }}
                            {{ risposte_form.text(class='form-text form-control', placeholder='Testo della risposta...') }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
                            {{ risposte_form.add(class='btn btn-primary') }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- end Modal -->

        <div class="page-header align-items-center mb-4">
            <h3 class="text-dark mb-0">Editor singola domanda</h3>
        </div>
        <div class="card mb-4 text-center col-md-7 mx-auto">
            <div class="card-header">
                <form method="POST">
                    {{ form.hidden_tag() }}
                    {{ form.text(class='form-control') }}
                    {{ form.submit(class='btn btn-success') }}
                </form>
            </div>
            {% if current_question.type_id == 2 or current_question.type_id == 3 %}
                <div class="card-body">
                    <div class="row" data-toggle="fieldset" id="domanda-fieldset">
                        <table>
                            {% for risposta in risposte %}
                                <tr>
                                    <td>{{ loop.index0 + 1 }}</td>
                                    <td>
                                        {% if risposta.text_html %}
                                            {{ risposta.text_html | safe }}
                                        {% else %}
                                            {{ risposta.text }}
                                        {% endif %}
                                    </td>
                                    <td>
                                        <form id="delete-question" method="POST" action="{{ url_for('quiz.delete_answer', answer_id=risposta.id, quiz_uuid=quiz_uuid) }}">
                                            <button type="submit" class="btn btn-outline-danger fas fa-trash-alt"></button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newAnswer"><i class="fas fa-plus fa-2x text-white"></i></button>
                </div>
            {% endif %}
        </div>
        <a href="{{ url_for('quiz.editor', edit_uuid=quiz_uuid) }}">← Torna all'editor del quiz</a>
    </div>

{% endblock %}