app/auth.py
"""
In questo modulo si trovano tutte le route riguardandi l'autenticazione nel sito
"""
from flask import Blueprint, render_template

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    return render_template("login.html")


@auth.route('/logout')
def logout():
    return render_template("index.html")


@auth.route('/signup')
def sign_up():
    """
    TODO: creare pagina html corretta e gestire gli input salvandoli nel database,
          eventualmente mandando email di conferma
    """
    return render_template("index.html")

app/templates/editor.html
{% extends 'layout.html' %}

{% block title %}Editor{% endblock %}

{% block page_content %}

    <div class="container-fluid">
        <!-- FLASH ERRORI -->
        <div class="row mx-auto">
            <div class="container">
                {% if editor_form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        <ul class="errors">
                            {% for field_name, field_errors in editor_form.errors|dictsort if field_errors %}
                                {% for error in field_errors %}
                                    <li>{{ editor_form[field_name].label }}: {{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>

    <!--
        Refactoring del quiz editor:
            al click sull'editor viene visualizzata la lista delle domande con il titolo e la descrizione editabili
            per ogni domanda c'è il pulsante edit che reindirizza a una pagina per fare l'editing della domanda
            per ogni domanda c'è il pulsante per cancellarla
            alla fine della pagina il pulsante '+' fa apparire un modal per creare la domanda.
    -->

        <!-- new qiestion Modal -->
        <div class="modal fade" id="newQuestion" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Nuovo quiz</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="" method="POST" role="form" class="user">
                        <div class="modal-body">
                            {{ form.hidden_tag() }}
                            {{ form.text(class='form-text form-control', placeholder='Testo della domanda') }}
                            <hr>
                            {{ form.type_id(class='form-select') }}
                            <hr>
                            {{ form.is_activated.label }} {{ form.is_activated(class='form-check-inline', id='is_activated',onclick='visibile()') }}
                            <div id="divInvis" style="visibility: hidden">
                                <br>
                                {{ form.activant.label }} {{ form.activant(class='form-select') }}
                                <br>
                                {{ form.id_activant_answer.label }} {{ form.id_activant_answer(class='form-select') }}
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
                            {{ form.submit(class='btn btn-primary') }}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- end Modal -->

        <!-- EDITOR -->
        <div class="page-header align-items-center mb-4">
            <h3 class="text-dark mb-0">Editor</h3>
        </div>
            <div class="card shadow mb-4 text-center col-md-7 mx-auto">
                <div class="card-header">
                    <form method="POST">
                    {{ editor_form.hidden_tag() }}
                    <h3>{{ editor_form.title(class='form-input') }}</h3>
                    {{ editor_form.description(class='form-control') }}
                    {{ editor_form.submit(class="btn btn-info") }}
                    </form>
                </div>
                <div class="card-body" data-toggle="fieldset" id="question-fieldset">
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Testo della domanda</th>
                                <th scope="col">Attivante</th>
                                <th scope="col">Tipo di domanda</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for domanda in current_quiz.questions %}
                                <tr data-toggle="fieldset-entry">
                                    <th scope="row">{{ loop.index0 + 1 }}</th>
                                    <td>
                                        {% if domanda.text_html %}
                                            {{ domanda.text_html | safe }}
                                        {% else %}
                                            {{ domanda.text }}
                                        {% endif %}
                                    </td>
                                    <td>{{ domanda.activant }}</td>
                                    <td>{{ tipi_domanda[domanda.type_id - 1].name }}</td>
                                    <td>
                                        <form id="edit-question" method="POST" action="{{ url_for('quiz.edit_question', question_id=domanda.id, quiz_uuid=current_quiz.uuid) }}">
                                            <button type="submit" class="btn btn-outline-info fas fa-edit"></button>
                                        </form>
                                        <form id="delete-question" method="POST" action="{{ url_for('quiz.delete', domanda_id=domanda.id) }}">
                                            <button type="submit" class="btn btn-outline-danger fas fa-trash-alt"></button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newQuestion"><i class="fas fa-plus fa-2x text-white"></i></button>
                </div>
            </div>
    </div>

    <script>
    function visibile(){
        if (document.getElementById('is_activated').checked)
        {
            document.getElementById('divInvis').style.visibility = 'visible';
        } else {
            document.getElementById('divInvis').style.visibility = 'hidden';
        }
    }
    </script>
{% endblock %}

app/templates/error.html
{% extends 'layout.html' %}

{% block title %}Error{% endblock %}

{% block page_content %}

    <div class="text-center mt-5">
        <div class="error mx-auto" data-text="{{ number }}">
            <p class="m-0">{{ number }}</p>
        </div>
        <p class="text-dark mb-5 lead">{{ message }}</p>
        <p class="text-black-50 mb-0">Sembra tu abbia trovato un glitch nel Matrix...</p><a href="/">← Torna alla Home</a>
    </div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {{ pagedown.html_head() }}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}{% endblock %} - Quizza che ti passa</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/fontawesome-all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/ionicons.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/fontawesome5-overrides.min.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap5.css">
    <link rel="shortcut icon" href="{{ url_for('static', filename = 'favicon/favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename = 'favicon/favicon.ico') }}" type="image/x-icon">
    {% block style %}{% endblock %}
</head>

{% block body %}
<body id="page-top">

    <div id="wrapper">
        <!-- LEFTSIDE NAVBAR -->
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion bg-gradient-primary p-0 fade show">
            <div class="container-fluid d-flex flex-column p-0"><a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{{ url_for('main.index') }}">
                    <div class="sidebar-brand-icon rotate-n-15"><i class="icon ion-document"></i></div>
                    <div class="sidebar-brand-text mx-3"><span>quiz4all</span></div>
                </a>
                <hr class="sidebar-divider my-0">
                <ul class="navbar-nav text-light" id="accordionSidebar">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.dashboard') }}"><i class="fas fa-home"></i><span>Crea un questionario</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.quizzes') }}"><i class="fas fa-table"></i><span>Compila un questionario</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.responses_overview') }}"><i class="fas fa-check"></i><span>Risposte ai tuoi questionari</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('main.profile', username=current_user['username']) }}"><i class="fas fa-user"></i><span>Profilo</span></a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}"><i class="far fa-user-circle"></i><span>Login</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.register') }}"><i class="fas fa-user-circle"></i><span>Registrati</span></a></li>
                    {% endif %}
                </ul>

                <div class="text-center d-none d-md-inline">
                    <button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button>
                </div>
            </div>
        </nav>

        <!-- PARTE RESTANTE DOPO LA NAVBAR LATERALE -->
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <!-- TOPBAR -->
                <nav class="navbar navbar-light navbar-expand bg-white shadow mb-4 topbar static-top">
                    <div class="container-fluid"><button class="btn btn-link d-md-none rounded-circle me-3" id="sidebarToggleTop" type="button"><i class="fas fa-bars"></i></button>
                        <ul class="navbar-nav flex-nowrap ms-auto">
                        
                            <div class="d-none d-sm-block topbar-divider"></div>
                            <!-- TOPBAR USERNAME RIGHT-UPPER CORNER -->
                            <li class="nav-item dropdown no-arrow">
                                {% if current_user.is_authenticated %}
                                <div class="nav-item dropdown no-arrow">
                                    <a class="dropdown-toggle nav-link" aria-expanded="false" data-bs-toggle="dropdown" href="#">
                                        <span class="d-none d-lg-inline me-2 text-gray-600 small">{{ current_user.username }}</span>

                                    </a>
                                    <!-- DROPDOWN MENU -->
                                    <div class="dropdown-menu shadow dropdown-menu-end animated--grow-in">
                                        <a class="dropdown-item" href="{{ url_for('main.profile', username=current_user['username']) }}"><i class="fas fa-user fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Profile</a>
                                        <!--<a class="dropdown-item" href="#"><i class="fas fa-cogs fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Settings</a>-->
                                        <!--<a class="dropdown-item" href="#"><i class="fas fa-list fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Activity log</a>-->
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{{ url_for('auth.logout') }}"><i class="fas fa-sign-out-alt fa-sm fa-fw me-2 text-gray-400"></i>&nbsp;Logout</a>
                                    </div>
                                </div>
                                {% else %}
                                    <a class="navbar-brand d-flex justify-content-center align-items-center sidebar-brand m-0" href="{{ url_for('auth.register') }}">
                                        <span style="color:rgb(52,91,204)">Registrati</span>
                                    </a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </nav>
                <!-- FLASH -->
                <div class="container-fluid">
                    <div class="row mx-auto">
                        <div class="container-fluid">
                            {% with messages = get_flashed_messages(with_categories=true) %}
                                {% if messages %}
                                    {% for category, message in messages %}
                                        <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                            {{ message }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            {% endwith %}
                        </div>
                    </div>
                <!-- CONTENUTO DINAMICO DELLA PAGINA -->
                    {% block page_content %}{% endblock %}
                </div>
            </div>

            <!-- FOOTER -->
            <footer class="bg-white sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>Progetto Basi di Dati 2020/21 Gruppo Math.Random</span></div>
                </div>
            </footer>
        </div>
        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>

    <!-- SCRIPTS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap5.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js"></script>

    <!-- FROM FILE -->
    <script src="{{ url_for('static', filename='js/bs-init.js') }}"></script>
    <script src="{{ url_for('static', filename='js/theme.js') }}"></script>
    {{ moment.include_moment() }}
    {% block script_part %}{% endblock %}
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
          config: ["MMLorHTML.js"],
          jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
          extensions: ["MathMenu.js", "MathZoom.js"]
        });
    </script>
</body>
{% endblock %}

</html>

app/templates/responses.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block page_content %}
    <style>
        a {
            text-decoration: none !important;
            color: black
        }
    </style>

<div class="container-fluid">
    <div class="d-sm-flex justify-content-between align-items-center mb-4">
        <h3 class="text-dark mb-0">Risposte per {{ current_quiz.title }}</h3>
        <!-- bottone per il dump CSV -->
        <a class="btn btn-primary btn-sm d-none d-sm-inline-block" role="button" href="{{ url_for('main.download', uuid=current_quiz.uuid) }}"><i class="fas fa-download fa-sm text-white-50"></i>&nbsp;Genera report .csv</a>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12">
                <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#overview" type="button" role="tab" aria-controls="home" aria-selected="true">Per Domanda</button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#single" type="button" role="tab" aria-controls="profile" aria-selected="false">Per Compilazione</button>
                    </li>
                </ul>
            </div>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview  -tab">
                    <div class="container">
                    {% for (domanda,tipo) in overview %}
                        <br><br>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="card shadow lg-12 mb-12">
                                    <div class="card-header d-flex justify-content-between align-items-center">
                                        <h3 class="text-primary fw-bold m-0">{{ domanda }}</h3>
                                    </div>
                                    <div class="card-body">
                                        {% if tipo == 1 %}
                                        <table class="table table-striped table-hover table-responsive-lg table-responsive-md table-responsive-sm">
                                            <thead>
                                                <tr>
                                                    <th scope="col text-center align-center">#</th>
                                                    <th scope="col text-center align-center">Risposta</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for risposta_s in overview[(domanda,tipo)] %}
                                                <tr>
                                                    <th scope="row">{{ loop.index }}</th>
                                                    <td>{{ risposta_s }}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                        {% else %}
                                        <table class="table table-striped table-hover table-responsive-lg table-responsive-md table-responsive-sm">
                                            <thead>
                                                <tr>
                                                    <th scope="col col-md-2">#</th>
                                                    <th scope="col col-md-5">Risposta</th>
                                                    <th scope="col col-md-5">Numero risposte</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for risposta_s in overview[(domanda,tipo)] %}
                                                <tr>
                                                    <th scope="row">{{ loop.index }}</th>
                                                    <td>{{ risposta_s }}</td>
                                                    <td>{{ overview[(domanda,tipo)][risposta_s] }}</td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
                <div class="tab-pane fade" id="single" role="tabpanel" aria-labelledby="single-tab">
                    <div class="container">
                        {% for i in risposte %}
                        <br><br>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="card shadow lg-12 mb-12">
                                    <div class="card-header d-flex justify-content-between align-items-center">
                                        <!-- TODO: aggiungere utente che ha immesso la risposta -->
                                        <h3 class="text-primary fw-bold m-0">Compilazione {{ loop.index }}</h3>
                                    </div>
                                    <div class="card-body">
                                        <table class="table table-striped table-hover table-responsive-lg table-responsive-md table-responsive-sm">
                                            <thead>
                                                <tr>
                                                    <th scope="col text-center align-center">Domanda</th>
                                                    <th scope="col text-center align-center">Risposta</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for j in risposte[i] %}
                                                <tr>
                                                    <th scope="row">{{ j }}</th>
                                                    <td>
                                                        {% if risposte[i][j]|length > 1 %}
                                                        <ul>
                                                            {% for k in risposte[i][j] %}
                                                            <li>{{ k }}</li>
                                                            {% endfor %}
                                                        </ul>
                                                        {% else %}
                                                                {{ risposte[i][j][0] }}
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>




</div>
{% endblock %}

app/templates/responses_overview.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% block page_content %}
    <style>
        a {
            text-decoration: none !important;
            color: black
        }
    </style>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="d-sm-flex justify-content-between align-items-center mb-4">
                <h3 class="text-dark mb-0">I Tuoi Questionari</h3>
            </div>
        </div>
    </div>
    <div class="row">
    {% for i in questionari %}
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="card shadow">
                        <div class="card-header d-flex justify-content-between align-items-center text-center">
                            <h3 class="text-primary fw-bold m-0">{{ i.title }}</h3>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{% if i.description_html %}
                                                {% if i.description_html|length > 150 %}
                                                    {{ i.description[:100]+'...' | safe }}
                                                {% else %}
                                                    {{ i.description_html | safe }}
                                                {% endif %}
                                            {% else %}
                                                {%  if i.description|length > 150 %}
                                                    {{ i.description[:100]+'...' }}
                                                {% else %}
                                                    {{ i.description }}
                                                {% endif %}
                                            {% endif %}</p>
                        </div>
                        <div class="card-footer">
                            <a href="{{ url_for('main.responses', quiz_uuid=i.uuid) }}" class="btn btn-primary">Visualizza Risposte</a>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
</div>





    {% block script_part %}
        <script src="{{ url_for('static', filename='js/chart.min.js') }}"></script>
    {% endblock %}
{% endblock %}

app/templates/visualize.html
{% extends 'layout.html' %}

{% block title %}Compila{% endblock %}

{% block page_content %}
    <!-- FLASH ERRORI -->
        <div class="row mx-auto">
            <div class="container">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        <ul class="errors">
                            {% for field_name, field_errors in form.errors|dictsort if field_errors %}
                                {% for error in field_errors %}
                                    <li>{{ form[field_name].label }}: {{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>


    <div class="page-header align-items-center mb-4">
            <h2>{{ current_quiz.title }}</h2>
            <p>
                {% if current_quiz.description_html %}
                    {{ current_quiz.description_html | safe }}
                {% else %}
                    {{ current_quiz.description }}
                {% endif %}
            </p>
    </div>
    <div class="card shadow mb-4 text-center col-md-7 mx-auto">
    <form method="POST">
        {{ form.hidden_tag() }}
        {% for domanda in domande %}
            <div class="card-header">
                {{ loop.index }}
                {% if domanda.text_html %}
                    {{ domanda.text_html | safe }}
                {% else %}
                    {{ domanda.text }}
                {% endif %}
            </div>
            <div class="card-body">
                {% set dom = getter(form, 'domanda' + to_str(loop.index0)) %}
                <!-- {% if domanda.is_activated %}
                    {% if domanda.type_id == 3 %}
                        {% for choiche in dom %}
                        <tr>
                            <td>{{ choiche(class='radio', disabled=True) }}</td>
                            <td>{{ choiche.label(class='form-label') }}</td>
                        </tr>
                        {% endfor %}
                    {% else %}
                        {{ dom(disabled=True) }}
                    {% endif %}
                {% else %} -->
                    {% if domanda.type_id == 3 %}
                        <table>
                        {% for choiche in dom %}
                        <tr>
                            <td>{{ choiche(class='radio') }}</td>
                            <td>{{ choiche.label(class='form-label') }}</td>
                        </tr>
                        {% endfor %}
                        </table>
                    {% elif domanda.type_id == 2 %}
                        <table>
                        {% for choiche in dom %}
                        <tr>
                            <td>{{ choiche }}</td>
                            <td>{{ choiche.label(class='form-label') }}</td>
                        </tr>
                        {% endfor %}
                        </table>
                    {% else %}
                        {{ dom() }}
                    {% endif %}
                {% endif %}
            </div>
        {% endfor %}
        <div class="card-footer">
            {{ form.submit }}
        </div>
    </form>
    </div>
{% endblock %}